/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\MiniModelMat.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/MiniModelMat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MiniModelKonti_v0.geometry} material={materials['Material.002']} position={[2.16, -3, -2.91]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/MiniModelMat.glb')
